-- Seed Data for Placement Preparation Portal

INSERT INTO "prep_resources" ("id", "title", "description", "url", "category", "platform", "sortOrder", "updatedAt") VALUES
  ('quantitative-aptitude-by-', 'Quantitative Aptitude by R.S. Aggarwal — Key Concepts', 'Master profit/loss, time & work, percentages, ratios, and number series.', 'https://www.indiabix.com/aptitude/questions-and-answers/', 'APTITUDE'::"PrepCategory", 'IndiaBIX', 1, NOW()),
  ('aptitude-practice-—-place', 'Aptitude Practice — Placement Season', 'Company-wise aptitude questions from TCS, Infosys, Wipro, and more.', 'https://www.geeksforgeeks.org/aptitude-questions-and-answers/', 'APTITUDE'::"PrepCategory", 'GeeksforGeeks', 2, NOW()),
  ('prepinsta-aptitude-questi', 'PrepInsta Aptitude Questions', 'Topic-wise aptitude practice with shortcuts and tricks.', 'https://prepinsta.com/aptitude/', 'APTITUDE'::"PrepCategory", 'PrepInsta', 3, NOW()),
  ('leetcode-—-top-interview-', 'LeetCode — Top Interview 150', 'Curated list of 150 must-solve problems covering arrays, strings, trees, graphs, and dynamic programming.', 'https://leetcode.com/studyplan/top-interview-150/', 'CODING'::"PrepCategory", 'LeetCode', 1, NOW()),
  ('striver''s-sde-sheet', 'Striver''s SDE Sheet', '191 problems organized by topic — the gold standard for placement prep DSA.', 'https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/', 'CODING'::"PrepCategory", 'TakeUForward', 2, NOW()),
  ('neetcode-150', 'NeetCode 150', 'Grouped by pattern: sliding window, two pointers, backtracking, etc.', 'https://neetcode.io/practice', 'CODING'::"PrepCategory", 'NeetCode', 3, NOW()),
  ('hackerrank-interview-prep', 'HackerRank Interview Preparation Kit', 'Warm-up challenges, data structures, algorithms, and problem solving.', 'https://www.hackerrank.com/interview/interview-preparation-kit', 'CODING'::"PrepCategory", 'HackerRank', 4, NOW()),
  ('verbal-ability-—-indiabix', 'Verbal Ability — IndiaBIX', 'Practice questions on reading comprehension, sentence correction, para jumbles.', 'https://www.indiabix.com/verbal-ability/questions-and-answers/', 'VERBAL'::"PrepCategory", 'IndiaBIX', 1, NOW()),
  ('english-grammar-&-vocabul', 'English Grammar & Vocabulary for Placements', 'Key grammar rules and vocabulary building for verbal sections.', 'https://www.geeksforgeeks.org/verbal-ability/', 'VERBAL'::"PrepCategory", 'GeeksforGeeks', 2, NOW()),
  ('logical-reasoning-—-india', 'Logical Reasoning — IndiaBIX', 'Blood relations, seating arrangements, coding-decoding, and syllogisms.', 'https://www.indiabix.com/logical-reasoning/questions-and-answers/', 'LOGICAL'::"PrepCategory", 'IndiaBIX', 1, NOW()),
  ('puzzles-&-logical-reasoni', 'Puzzles & Logical Reasoning — GeeksforGeeks', 'Popular logical puzzles asked in tech company interviews.', 'https://www.geeksforgeeks.org/puzzles/', 'LOGICAL'::"PrepCategory", 'GeeksforGeeks', 2, NOW()),
  ('os,-dbms,-cn-—-core-cs-co', 'OS, DBMS, CN — Core CS Concepts', 'Revision notes for Operating Systems, DBMS, and Computer Networks.', 'https://www.geeksforgeeks.org/gate-cs-notes-gq/', 'TECHNICAL'::"PrepCategory", 'GeeksforGeeks', 1, NOW()),
  ('system-design-primer', 'System Design Primer', 'Learn how to design large-scale systems — essential for senior roles.', 'https://github.com/donnemartin/system-design-primer', 'TECHNICAL'::"PrepCategory", 'GitHub', 2, NOW()),
  ('oops-concepts-for-intervi', 'OOPs Concepts for Interviews', 'Encapsulation, inheritance, polymorphism, abstraction with examples.', 'https://www.geeksforgeeks.org/object-oriented-programming-oops-concept-in-java/', 'TECHNICAL'::"PrepCategory", 'GeeksforGeeks', 3, NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "resume_assets" ("id", "title", "type", "description", "fileUrl", "content", "updatedAt") VALUES
  ('single-column-ats-friendl', 'Single Column ATS-Friendly Template', 'TEMPLATE'::"AssetType", 'Clean, single-column resume template optimized for Applicant Tracking Systems. No graphics, no tables, just structured sections.', 'https://docs.google.com/document/d/1wdkS3BxMkfP6IKvMg3_dmqxQEiPBfXqb/edit', NULL::jsonb, NOW()),
  ('two-column-modern-ats-tem', 'Two-Column Modern ATS Template', 'TEMPLATE'::"AssetType", 'A modern two-column layout that still passes ATS parsing. Skills sidebar with experience timeline.', 'https://docs.google.com/document/d/1mJQ8BxYeC_wPqLHPmH3Wj2yZ4TdPsN8e/edit', NULL::jsonb, NOW()),
  ('fresher-resume-template', 'Fresher Resume Template', 'TEMPLATE'::"AssetType", 'Designed for fresh graduates — emphasizes projects, internships, and education over experience.', 'https://docs.google.com/document/d/1gKgP8wLfM3hZqY3r5Xs2yTvBfQ9nDcJm/edit', NULL::jsonb, NOW()),
  ('action-verbs-—-technical-', 'Action Verbs — Technical Roles', 'ACTION_WORDS'::"AssetType", 'Power verbs categorized for software engineering, data science, and IT roles.', NULL, '{"development":["Architected","Built","Coded","Debugged","Deployed","Developed","Engineered","Implemented","Integrated","Migrated","Optimized","Programmed","Refactored","Shipped"],"leadership":["Coordinated","Directed","Led","Managed","Mentored","Orchestrated","Oversaw","Spearheaded","Supervised"],"analysis":["Analyzed","Assessed","Audited","Benchmarked","Evaluated","Investigated","Measured","Modeled","Quantified","Researched","Tested","Validated"],"communication":["Advised","Collaborated","Consulted","Documented","Presented","Proposed","Recommended","Reported","Trained"],"achievement":["Accelerated","Achieved","Boosted","Delivered","Enhanced","Exceeded","Improved","Increased","Launched","Pioneered","Reduced","Streamlined","Transformed"]}'::jsonb, NOW()),
  ('action-verbs-—-non-techni', 'Action Verbs — Non-Technical & Management Roles', 'ACTION_WORDS'::"AssetType", 'Power verbs for business, marketing, finance, and HR roles.', NULL, '{"strategy":["Authored","Conceptualized","Designed","Devised","Formulated","Initiated","Planned","Strategized"],"operations":["Administered","Consolidated","Established","Executed","Facilitated","Organized","Processed","Restructured"],"growth":["Amplified","Cultivated","Drove","Expanded","Generated","Grew","Maximized","Scaled"],"finance":["Allocated","Budgeted","Calculated","Forecasted","Negotiated","Procured","Projected","Reconciled"]}'::jsonb, NOW()) ON CONFLICT ("id") DO NOTHING;
